name: Update Audible Books

on:
  schedule:
    - cron: '0 7 * * *'   # Midnight EST

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-books:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python scraper.py

      - name: Run manual scraper
        run: python make_manual_json.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add books.json
          git add manual_books.json

          git diff --cached --quiet || git commit -m "Auto update books"

          git push
